### PR TITLE
Added a smart PHP time library: `zjkal/time-helper`

### PR DESCRIPTION
**Pull request by zjkal**
Added a useful PHP time library

### CODE REVIEW

**Comment by dereuromark** [comment]
Libraries including docs must be written in English

**Comment by dereuromark** [comment]
A lot of static 
What's the benefit over battletested ones like chronos?

**Comment by zjkal** [comment]
There is no doubt that carbon is the best. But time-helper is simpler and more suitable for novices. In addition, there is one more choice for PHP developers. That's it.

**Comment by alexkart** [comment]
Thanks for the suggestion. However, the library does not meet certain criteria specified in the [Contribution Guidelines](https://github.com/ziadoz/awesome-php/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
