### PR TITLE
Added Kahlan in Testing

### PR DESCRIPTION
**Pull request by m1ome**
I would like to suggest to add the [Kahlan](https://github.com/crysalead/kahlan) library in your repository.
Kahlan is a "RSpec/JSpec-like" testing libraries (like **Peridot** or **Pho**) but with a wider scope. It's a full featured framework which bundles together all tools to speed up test developpement.

Main features are:

- Simple API
- Small code base (~10 times smaller than PHPUnit)
- Fast Code Coverage metrics (xdebug required) (built-in exporter for Coveralls, Code Climate, Scrutinizer)
- Handy stubbing system (no more mockery or prophecy required)
- Set stubs on your class methods directly (i.e allows dynamic mocking)
- Ability to Monkey Patch your code (i.e. allows replacement of core functions/classes on the fly without any PECL extension required)
- Check called methods on your class/instances directly
- Built-in Reporters/Exporters (Terminal, Coveralls, Code Climate, Scrutinizer, Clover)
- Extensible, customizable workflow

### CODE REVIEW

**Comment by jails** [comment]
:+1:

**Comment by urosgruber** [comment]
:+1:

**Comment by cvermeul** [comment]
+1

**Comment by jails** [comment]
Not sure if this would change your mind, but Kahlan is now present in http://www.phptherightway.com/#testing and still the only one with Monkey Patching capabilities https://twitter.com/jeffrey_way/status/651051685197053952

**Comment by markalexandercastillo** [comment]
:+1:

**Comment by jails** [comment]
Hi @ziadoz, Kahlan has now 175 stars, so either merge or close this PR please.
Thank you.

**Comment by m1ome** [comment]
@josegonzalez :+1:

**Pull request merged**
