### PR TITLE
Added codeigniter as a framework

### PR DESCRIPTION
**Pull request by kavinda1995**
Since **Codeigniter** is a well known and popular framework for PHP. I added it to the frameworks section.

### CODE REVIEW

**Comment by kavinda1995** [comment]
Since Codeigniter is a well known and popular framework for PHP. I added it to the frameworks section.

**Comment by ackintosh** [comment]
It seems duplicate of https://github.com/ziadoz/awesome-php/pull/786 👀

**Comment by kavinda1995** [comment]
Still codeigniter hasn't been added right?

**Comment by ziadoz** [comment]
There are no plans to add CodeIgnitor. Thanks for the suggestion though.

**Comment by savioret** [comment]
What are the reasons ?

**Pull request closed without merging**
