### PR TITLE
[authentication and authorization] AlloVince/EvaOAuth

### PR DESCRIPTION
**Pull request by AlloVince**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you rebase this onto master?

**Comment by AlloVince** [comment]
Hi, I just sync master to newest

**Comment by josegonzalez** [comment]
We already have a few solutions to oauth 1/2 client and server, so I'll be closing this.

This list isn't meant to house *every* php package, just the clear winners. I'd rather we concentrate on making a few great than creating a plethora of options.

**Comment by AlloVince** [comment]
Hi, It is ok to accept this result, but I don't understand what is "winner" means, I took a quick view on some OAuth repos already added in awesome-php list, such as this one https://github.com/ruudk/twitteroauth or this one https://github.com/hybridauth/hybridauth, these repos not even have one line test code, or don't have any document, why you think these repo are better and consider them as "winners"

**Comment by josegonzalez** [comment]
In this case I'm talking about the OAuth 1/2 client and server modules from ThePhpLeague.

**Comment by AlloVince** [comment]
OK, if you have a clear criteria for judging winners, you'd better remove all repos which not winners, otherwise make PR contributors feel confuse.

**Comment by josegonzalez** [comment]
I believe @ovr just replaced HybridAuth with SocialAuth. I'll replace the ruudk version with the non-forked version as well. Thanks for the feedback!

**Pull request closed without merging**
