### PR TITLE
Added zend-diactoros and updated middlewares

### PR DESCRIPTION
**Pull request by ojhaujjwal**
* I have added `zend-diactoros` which is probably the best PSR-7 implementation.
* Conduit has been deprecated in favour of zend-stratigility.
* Relay looks like a promising PSR-7 middleware dispatcher.

I am surprised that there is not much in here about PSR-7.

### CODE REVIEW

**Comment by colinodell** [comment]
+1

**Comment by edigu** [comment]
+1

**Comment by rougin** [comment]
+1

**Comment by josegonzalez** [comment]
Please split this into two separate PRs.

**Pull request closed without merging**
