### PR TITLE
Create 中文说明

### PR DESCRIPTION
**Pull request by grey5659**
中文翻译

### CODE REVIEW

**Comment by josegonzalez** [comment]
Sorry, I don't understand what this file is for?

**Comment by grey5659** [comment]
It doesn't matter. I just started using github.A Chinese Translation~

**Comment by josegonzalez** [comment]
Gotcha.

**Comment by Jaggle** [comment]
@woooool ,try to describe what you have did carefully, then the others who don't speak Chinese will understand you (大哥能有翻译之劳确实有不错)

**Pull request closed without merging**
