### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by YannickFricke**
Fixed a typo.
"Psalm" was named "Pslam".

### CODE REVIEW

**Comment by YannickFricke** [comment]
@ziadoz Any updates on  this?

**Comment by ziadoz** [comment]
@YannickFricke I'm happy to merge this once the conflicts are fixed.

**Comment by YannickFricke** [comment]
@ziadoz There aren't any conflicts?
Or do I just don't see them?

**Comment by ziadoz** [comment]
@YannickFricke I've sorted his myself. Thanks for point this typo out.

**Pull request closed without merging**
