### PR TITLE
Number guidelines in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tleb**
Numbered guidelines in CONTRIBUTING.md for easier reference.

### CODE REVIEW

**Comment by tleb** [comment]
@ziadoz Anything I can do for this PR to be merged?

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by ziadoz** [comment]
I'm not sure they really need to be numbered, since they aren't really in any kind of order. Thanks though.

**Comment by tleb** [comment]
I had problems referencing a specific one since nothing identifies them.

**Comment by armababy** [comment]
:+1:

**Comment by Rayne** [comment]
(Automatic) Numbering seems useful at the first glance, but isn't suitable for referencing as the guidelines and their order will change some day.

**Comment by tleb** [comment]
@Rayne I am not talking about automatic numbering: if we need a new guideline, just add a new number, but do not delete previous guidelines, ~~cross them through~~.

**Pull request closed without merging**
