### PR TITLE
Add Sukarix framework.

### PR DESCRIPTION
**Pull request by GhaziTriki**

### CODE REVIEW

**Comment by ziadoz** [comment]
See: https://github.com/ziadoz/awesome-php/pull/1288

**Comment by GhaziTriki** [comment]
@ziadoz Sukarix is different from F3.

**Comment by ziadoz** [comment]
@GhaziTriki It says it's powered by Fat Free on the website.

**Comment by GhaziTriki** [comment]
It is like Laravel using Symfony components (they don't mention that on their website), but not a dry clone of F3.

**Comment by ziadoz** [comment]
I've no plans to add Fat Free or anything built on or with it onto the list, sorry.

**Pull request closed without merging**
