### PR TITLE
[PHP Installation] Add Brew PHP Switcher

### PR DESCRIPTION
**Pull request by jk2K**

### CODE REVIEW

**Comment by jadb** [comment]
Thanks for the submission.

Is this similar to https://github.com/phpbrew/phpbrew? How does it differentiate?

**Comment by jk2K** [comment]
`Brew PHP switcher` can switch Homebrew's PHP module location automatically in the Apache config, make full use of `Homebrew`, more easy

`Brew PHP switcher` can install php extension with `Homebrew`, while `PHPBrew` install php extension by itself

**Comment by jadb** [comment]
Thanks for the update. I will let @josegonzalez look at this, he is a homebrew expert.

**Comment by ziadoz** [comment]
Thanks for the suggestion.

**Pull request closed without merging**
