### PR TITLE
[data structures and storage] Athari/YaLinqo

### PR DESCRIPTION
**Pull request by Athari**
[YaLinqo](https://github.com/Athari/YaLinqo) ([documentation](http://athari.github.io/YaLinqo), [packagist](https://packagist.org/packages/athari/yalinqo), other links in the readme).

P. S. Another LINQ library is already here (PINQ), but its quality is... [questionable](http://www.codeproject.com/Articles/997238/LINQ-for-PHP-comparison-YaLinqo-Ginq-Pinq) (I may be biased, but you can see the results and judge youself).

### CODE REVIEW

**Comment by jkufner** [comment]
Referenced article is very good reading. It should be linked from the awesome list too.

**Comment by Athari** [comment]
@jkufner The article doesn't seem to fit the awesome list's format. :grinning:

**Comment by jkufner** [comment]
@Athari I meant to add the link next to links to libraries. Like a note on page margin, not as awesome list item.

**Comment by Athari** [comment]
@jkufner No other items have links like this. I don't think the repository's maintainers will approve stretching the rules for just one library. :grinning:

Also, if links are to be added, I think introductory articles would be more appropriate, but this article isn't introductory by any stretch.

**Comment by josegonzalez** [comment]
Do you mind rebasing this onto master?

**Comment by josegonzalez** [comment]
Actually, this is already in master. Closing.

**Pull request closed without merging**
