### PR TITLE
[code analysis] monque/PHP-Migration

### PR DESCRIPTION
**Pull request by monque**
This is a static analyzer for PHP version migration and compatibility checking.

It can suppose your current code running under the new version of PHP then do checking, and provide advice and treatment.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you rebase this onto master?

**Comment by monque** [comment]
done

**Comment by monque** [comment]
Is any one handle this ?

**Comment by monque** [comment]
So quick, thanks 👍

**Pull request merged**
