### PR TITLE
Adding new dev env: devilbox

### PR DESCRIPTION
**Pull request by cytopia**
This PR will add another PHP Development Environment: [devilbox](https://github.com/cytopia/devilbox).

> The devilbox is a modern and highly customisable dockerized PHP stack supporting full LAMP and MEAN and running on all major platforms. The main goal is to easily switch and combine any version required for local development. It supports an unlimited number of projects for which vhosts and DNS records are created automatically. Email catch-all and popular development tools will be at your service as well. Configuration is not necessary, as everything is pre-setup with mass virtual hosting.

### CODE REVIEW

**Comment by josegonzalez** [comment]
How is this better or worse than any of the existing solutions?

**Comment by cytopia** [comment]
This is not better or worse than the existing solutions. It is a completely different approach. The devilbox already gives you a fully functional development environment without you having to set up anything. The main benefit is that you can always switch between PHP 54, 55, 56, 70, 71, 72 and HHVM.

It will also allow you to have unlimitted projects without having to setup vhost configurations

**Comment by cytopia** [comment]
@josegonzalez is this going to be merged or closed?

**Comment by dereuromark** [comment]
If this gets rebased I think it can be merged 
I use it too and it is quite nice to be used

**Comment by dereuromark** [comment]
Never mind, doesnt seem maintained anymore, stopped at 8.2.1

**Pull request closed without merging**
