### PR TITLE
add Fiery  Distributed tracking system

### PR DESCRIPTION
**Pull request by xcl3721**
Distributed tracking system

### CODE REVIEW

**Comment by xcl3721** [comment]
waiting the passed ....

**Comment by smalleyes** [comment]
Good job

**Comment by Rayne** [comment]
This is your [third PR for the same project](https://github.com/ziadoz/awesome-php/pulls/xcl3721).

**Comment by xcl3721** [comment]
yes sir~ will close this two……

**Comment by xcl3721** [comment]
ok the other closed……

**Comment by mablae** [comment]
This is a JAVA project...

**Comment by xcl3721** [comment]
sure but this project service for the php project ,i hava cpp version too. it's need more things such as kafka elasticsearch and librocksdb ....will open soon this version. this version  is tiny simple and easy for deploy good for the small business company

**Comment by mablae** [comment]
...

**Pull request closed without merging**
