### PR TITLE
[frameworks] iceframework

### PR DESCRIPTION
**Pull request by iGusev**
Simple and fast PHP framework delivered as C-extension.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you rebase this onto master?

**Comment by iGusev** [comment]
@josegonzalez done

**Comment by kamilsk** [comment]
@iGusev, and again there is a problem

Reason:
- https://github.com/ziadoz/awesome-php/pull/404/files
- https://github.com/ziadoz/awesome-php/issues/617

Can you update pr?

**Comment by iGusev** [comment]
@kamilsk yep

**Pull request merged**
