### PR TITLE
Adding Cygnite Framework in the list

### PR DESCRIPTION
**Pull request by sanjoydesk**
Adding Cygnite PHP framework in framework list.

### CODE REVIEW

**Comment by sanjoydesk** [comment]
Description added for the commit and for the entry. Can you please have it merged? Thanks in advance!!

**Comment by sanjoydesk** [comment]
@VarCI-bot @ziadoz @Pawka can you please have this merged. Thanks in advance.

**Comment by josegonzalez** [comment]
This is a pretty new framework (a year or so old) with not many active users in comparison to the others. While we appreciate the effort and wish you luck, this list isn't for self-promotion, so I'll close this. Feel free to submit at a later date once your community has grown :)

**Comment by sanjoydesk** [comment]
Thanks for your words.. But my dear friend @josegonzalez I think this repository made to help PHP community. If it is, you should encourage any contribution to the open source. Not all projects initially itself gets huge community support. And I don't see anywhere mentioned that this list of only for Popular projects. Just have a look at the project and I believe if you add into the list it will help developers who are building small to mid level projects.

**Comment by josegonzalez** [comment]
From our [CONTRIBUTING.md](https://github.com/ziadoz/awesome-php/blob/master/CONTRIBUTING.md):

> Self-promotion is frowned upon, so please consider seriously whether your project meets the criteria before opening a pull request, otherwise it may be closed without being reviewed.

In the case of a framework, we have slightly different criteria and higher standards, hence the non-inclusion of your project on our list. Sorry about that, but that isn't going to change soon.

**Comment by sanjoydesk** [comment]
Alright my friend!! Thank you!

**Pull request closed without merging**
