### PR TITLE
Added YaLinqo.

### PR DESCRIPTION
**Pull request by saulotoledo**
YaLinqo is one of the three major .NET's LINQ to Objects implementations for PHP.

### CODE REVIEW

**Comment by jadb** [comment]
Rebase please - merge conflicts for now.

**Comment by saulotoledo** [comment]
@jadb done.

**Comment by josegonzalez** [comment]
Needs another rebase now that the other pr is merged.

**Comment by saulotoledo** [comment]
@josegonzalez done.

**Pull request merged**
