### PR TITLE
Add Climb

### PR DESCRIPTION
**Pull request by vinkla**
A Composer version manager tool.

### CODE REVIEW

**Comment by ecolinet** [comment]
Is it possible to get the same requirements between composer (5.3+) and
Climb (5.5+) ?

Thanks !

2015-11-06 8:22 GMT+01:00 Vincent Klaiber <notifications@github.com>:

**Comment by vinkla** [comment]
Yeah, maybe. Though, we have targeted 5.5+ since older version aren't maintained anymore.

**Comment by vinkla** [comment]
Any update on this?

**Comment by bocharsky-bw** [comment]
:+1: for Climb.

**Comment by Bavragor** [comment]
:+1: for Climb

**Comment by vinkla** [comment]
@bocharsky-bw @Bavragor thanks guys!

**Comment by vinkla** [comment]
@ziadoz @josegonzalez anything I can do to get this merged? Let me know.

**Comment by jadb** [comment]
Thanks!

**Comment by vinkla** [comment]
Thanks!

**Pull request merged**
