### PR TITLE
Add Square PHP SDK

### PR DESCRIPTION
**Pull request by havenwood**
The [Square PHP SDK](https://github.com/square/connect-php-sdk) provides access to [payments and other Square APIs](https://squareup.com/us/en/developers).

### CODE REVIEW

**Comment by bobbilee19** [comment]
@havenwood ping to follow up on this one

**Comment by jadb** [comment]
Sorry for late reply. 

This one should definitely make the list as an official SDK, but could someone please put it in its alphabetical order as part of the 3rd party APIs section?

**Comment by havenwood** [comment]
I alphabetized and rebased. Thank you!

**Comment by jadb** [comment]
Thank you! 👍

**Pull request merged**
