### PR TITLE
add Docker to Infrastructure section

### PR DESCRIPTION
**Pull request by jaschweder**
Added Docker has infrastructure option

### CODE REVIEW

**Comment by jadb** [comment]
Sorry, not sure how that fits here. There is nothing PHP specific (compared to the other in same category).

**Comment by jaschweder** [comment]
@jadb there are other tools in another sections, like DBV in Web Applications, Ansible in Development Enviorment, all tools in Deployment section, etc, that didn't are specific for PH, so if this is a rule here, please remove all those.

Otherwise, Docker is a generic tool that can be use to develop PHP applications, for a lot of uses cases.

**Comment by josegonzalez** [comment]
@jaschweder Docker isn't infrastructure. If anything, it should be in Development Environment.

**Comment by jadb** [comment]
@jaschweder sorry I maybe could have been clearer. I meant not a good fit for that specific category, not for the list as a whole.

**Comment by jaschweder** [comment]
@jadb thanks for clarify :) I'll change the category of Docker to "Development Enviroment" as suggested

**Comment by jaschweder** [comment]
done

**Comment by jadb** [comment]
thanks @jaschweder!

**Pull request merged**
