### PR TITLE
[strings] fukuball/jieba-php

### PR DESCRIPTION
**Pull request by fukuball**
Add Jieba to Strings, "Jieba" (Chinese for "to stutter”) is a Chinese
text segmentation library for natural language processing.

### CODE REVIEW

**Comment by fukuball** [comment]
Chinese segmentation is not as easy as other language, for example, sentence “When approaching” we can just use space to cut the sentence to words [When, approaching], but “When approaching” in Chinese “即將來臨時” we can't apply any easy way to cut sentence to meaningful words. Jieba can cut “即將來臨時” to meaningful words like [即將, 來臨, 時] or [即, 將來, 臨時].

Chinese segmentation is the foundations of Chinese natural language processing. So, I think we can add this library to awesome-php.

By the way, this library is a PHP port of Python's [jieba](https://github.com/fxsjy/jieba).

**Comment by jadb** [comment]
While I understand that the project is for working with the Chinese language; having the README entirely in Chinese makes it un-interesting to add to this list as the vast majority of people will not understand it.

I am closing this for now, but please re-submit once you have a minimal english description on the project's README as it looks promising and gained some popularity already (I don't understand Chinese, so just looked at stars).

**Comment by fukuball** [comment]
@jadb I do have [English document](https://github.com/fukuball/jieba-php#jieba-php-english-document), just scroll down to see the doc. jieba-python is in [awesome python](https://github.com/fxsjy/jieba), and it's important for Chinese natural language processing, I think PHP should have one like this.

PHP is weak in machine learning, but many people still want to make PHP better in machine learning, jieba-php can use in Chinese natural language processing for machine learning. I hope jieba-php can put in this list, so that someone need it, they can find it.

**Comment by josegonzalez** [comment]
Can you rebase this? I'd actually like to pull it in. Also please ensure it is in the right place alphabetically.

**Comment by fukuball** [comment]
@josegonzalez I just rebase the repo~ Please review my pull request, thanks!

**Pull request merged**
