### PR TITLE
[Data Structure and Storage] Add msgpack.php

### PR DESCRIPTION
**Pull request by rybakit**
https://github.com/rybakit/msgpack.php

### CODE REVIEW

**Comment by josegonzalez** [comment]
I like it. Are there other pure php alternatives? Cursory search says no, just wanted to check though.

**Comment by rybakit** [comment]
I'm not aware of any _working_ implementation of the MessagePack protocol in pure php. Actually, this library was born because I didn't find anything suitable ;)

**Comment by rybakit** [comment]
@josegonzalez ping

**Comment by ziadoz** [comment]
Thanks, I've merged this.

**Pull request merged**
