### PR TITLE
[exercises] danrevah/php-exercises

### PR DESCRIPTION
**Pull request by danrevah**
GitHub Repository: https://github.com/danrevah/php-exercises

Based on the same idea of the kolodny javascript exercises (https://github.com/kolodny/exercises).
using the TDD approach to practice.

### CODE REVIEW

**Comment by tleb** [comment]
@danrevah: If you give exercises to beginners, I think you should give a good example with your code. In your `test.php`, you declare new symbols and you have logic. This goes against most standards.

Anyway, I like the test-unit-verified exercises idea.

**Comment by danrevah** [comment]
@tleb Thank you for your feedback, but in each exercise directory there's a readme file that explains exactly what needs to be done.
I think it's pretty straightforward.  Anyway if you have any ideas on how to improve it, you are more than welcome to suggest pull request.

**Comment by tleb** [comment]
What I am saying is that if a beginner looks at your code (curiousity can be an advantage), they will see logic and symbol declarations in the same file, which is bad a bad practice.

**Comment by danrevah** [comment]
I don't agree with you. It's following the same idea behind the kolodny js exercises which are aimed to beginners as well.

**Comment by josegonzalez** [comment]
Can you rebase this onto master?

**Comment by danrevah** [comment]
@josegonzalez https://github.com/ziadoz/awesome-php/pull/637

**Pull request closed without merging**
