### PR TITLE
Alphabetize contents. Add Configuration section

### PR DESCRIPTION
**Pull request by m1**

### CODE REVIEW

**Comment by m1** [comment]
@ziadoz If you didn't want the contents alphabetized let me know, I'll revert and you can pull in just the configuration section -- just thought it would be easier to scan when looking for a specific library.

**Comment by marcuschaplais** [comment]
+1 :+1:

**Comment by josegonzalez** [comment]
Closing since this would break all existing PRs. Can you add your configuration section in a separate PR?

**Comment by m1** [comment]
Yep will do. P.S. Hi jose!

**Comment by josegonzalez** [comment]
I'm fucking everywhere!

**Comment by jkufner** [comment]
What about second file, which would be generated from the current, primary, README.md? It should be relatively easy to collect all links and sort them. Then we can have multiple views on the same list.

**Comment by josegonzalez** [comment]
I don't want to maintain two lists, so no. Alphabetizing can wait :)

**Comment by ziadoz** [comment]
Yeah, it can definitely wait.

**Comment by m1** [comment]
https://github.com/ziadoz/awesome-php/pull/557 @josegonzalez

**Pull request closed without merging**
