### PR TITLE
Add phptrace

### PR DESCRIPTION
**Pull request by shafreeck**
phptrace is a tool to trace php function execution flow.

### CODE REVIEW

**Comment by shafreeck** [comment]
Is any one handle this ?

**Comment by monque** [comment]
Friendly ping @ziadoz

**Comment by ziadoz** [comment]
I think you have a typo in the URL (you're missing `e`). I've made a note of this in the PECL/C package list I've got going.

**Comment by shafreeck** [comment]
@ziadoz I did not find what you said the typo. The link works and I am sure it is correct.

**Comment by ziadoz** [comment]
Ah. I think I must have copied it a letter short. My mistake.

**Pull request closed without merging**
