### PR TITLE
add code igniter to Frameworks

### PR DESCRIPTION
**Pull request by hadyandev**
CodeIgniter is a powerful PHP framework with a very small footprint, built for developers who need a simple and elegant toolkit to create full-featured web applications.

### CODE REVIEW

**Comment by hadyandev** [comment]
CodeIgniter is a powerful PHP framework with a very small footprint, built for developers who need a simple and elegant toolkit to create full-featured web applications.

**Comment by donis** [comment]
Please search the repository for previous pull requests adding CodeIgniter, they were not accepted for a reason.

**Comment by tandrus** [comment]
CodeIgniter was not accepted, because it supported old versions of PHP.
Now CodeIgniter 4 requires PHP 7.1 or higher.

**Comment by vnay92** [comment]
But, CodeIgniter 4 is still in alpha version. Not yet released fully. Does it count?

**Comment by tandrus** [comment]
> But, CodeIgniter 4 is still in alpha version. Not yet released fully. Does it count?

Yes, agree.

**Comment by donis** [comment]
But given this is an "awesome" list, not just a list of everything, it should be proven in production environments also and mature a bit. Otherwise how will this be different from packagist list?

**Pull request closed without merging**
