### PR TITLE
Add Better Reflection to Code Analysis section

### PR DESCRIPTION
**Pull request by asgrim**
Add Better Reflection to Code Analysis section.

### CODE REVIEW

**Comment by mablae** [comment]
@ziadoz Please merge right away, this lib is awesome and does not need further explanations!

**Comment by jadb** [comment]
Thanks!

**Comment by ziadoz** [comment]
@asgrim @mablae I'd made a note to look at this after I'd heard it mentioned at a conference, but I guess I never got around to it, so thanks for the submission.

**Comment by asgrim** [comment]
@ziadoz gimme a shout if you come across any issues if/when you do manage to check it out :)

**Pull request merged**
