### PR TITLE
[event] amphp/amp

### PR DESCRIPTION
**Pull request by kelunik**
https://github.com/amphp/amp

### CODE REVIEW

**Comment by kelunik** [comment]
What's the criteria to merge this?

**Comment by ephrin** [comment]
like it. I think it worth. At least reactors implementation are worth spreading.

**Comment by kelunik** [comment]
*push*

**Comment by josegonzalez** [comment]
Something something 100 prs looks scary. I'm categorizing things now so we can get a better handle on shit.

**Pull request merged**
