### PR TITLE
Add Lumen by Laravel

### PR DESCRIPTION
**Pull request by Stichoza**
This is actually the most awesome micro-framework ever created on PHP. Faster than Slim and Silex.

Definitely it should be number one in micro-frameworks list.

### CODE REVIEW

**Comment by efik** [comment]
Duplicated: #367 :)

**Comment by Stichoza** [comment]
Haha :smile:  then why don't you merge any of lumen PRs? :smile:

**Comment by ziadoz** [comment]
Thanks, I've merged this.

**Comment by Stichoza** [comment]
@efik Oh, I thought you were the maintainer of this repo, so my previous comment is for @ziadoz.

@ziadoz Thanks for merge! I hope @efik is not upset about this.

**Comment by efik** [comment]
It's ok:) 
Cheers!

**Pull request merged**
