### PR TITLE
Add MediaEmbed

### PR DESCRIPTION
**Pull request by dereuromark**
https://github.com/dereuromark/MediaEmbed

A stand-alone utility library that generates HTML embed tags for audio or video located on a given URL. It also parses and validates given media URLs.

It currently works with 150+ services, including the most important ones like
- YouTube
- Dailymotion
- MyVideo
- Vimeo

I can provide also a link to a demo sandbox-site if that is of interest.

### CODE REVIEW

**Comment by dereuromark** [comment]
The 3 fails are unrelated, other libraries.

**Comment by dereuromark** [comment]
Demo / Sandbox-Link for trying it out: https://sandbox.dereuromark.de/sandbox/media-embed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiIdRNFY18wQ

**Comment by dereuromark** [comment]
Whats the hold up here?

**Comment by donis** [comment]
what's the rush?

**Comment by donis** [comment]
If you read the [contributing](https://github.com/ziadoz/awesome-php/blob/master/CONTRIBUTING.md) guidelines they say as follows:

> Unfortunately, not every library, tool or framework can be considered for inclusion. The aim of Awesome PHP is to be a concise list of noteworthy and interesting software written in modern PHP. Therefore, suggested software should:
> 
> 1. Be widely recommended regardless of personal opinion
> 2. Well known or discussed within the PHP community
> 3. Be unique in its approach or function
> 4. Fill a niche gap in the market
>
> Self-promotion is frowned upon, so please consider seriously whether your project meets the criteria before opening a pull request, otherwise it may be closed without being reviewed.

Since it's a self-promoting PR - it breaks the rules.

**Comment by dereuromark** [comment]
If it does match other criteria and should rather than must, I would say that your feedback is rather breaking some rules :) It does provide a rather well defined benefit over just simply letting it rust there in the dark as never merged PR. So maybe help promoting instead of dismissing?

**Comment by dereuromark** [comment]
Also, I meant mainly constructive feedback, since there was none whatsoever. I didnt talk about merge in general at this point. Your feedback however is not constructive.

**Comment by donis** [comment]
I was just wondering why the push for this :) Here's some constructive feedback.

This PR has a conflict so most likely it needs to be rebased on a latest version.

As for the library (again, just following the contribution guide)
- it's 5.6+ instead of 7.0+
- it is not PSR compliant
- how is it different from already included https://github.com/oscarotero/Embed?

**Pull request closed without merging**
