### PR TITLE
Add CakePHP to list of frameworks

### PR DESCRIPTION
**Pull request by markstory**

### CODE REVIEW

**Comment by dereuromark** [comment]
last "authored on 11 Dec 2014"
I wonder why CakePHP is still not in the list with the other frameworks yet? @ziadoz

**Comment by ziadoz** [comment]
Once CakePHP 3.0 releases I'll merge this. I'm quite behind on tickets lately, but I've got a lot of stuff going on right now. Rest assured I'll start merging tickets again soon.

**Comment by dereuromark** [comment]
Cool :+1: 
Rest assured Cake3 RC is already as good as they come ;)

**Comment by markstory** [comment]
Thanks for merging @ziadoz :clap:

**Comment by ziadoz** [comment]
No problem. CakePHP 3 looks great by the way.

**Comment by lorenzo** [comment]
:clap:

**Pull request merged**
