### PR TITLE
Add Siler

### PR DESCRIPTION
**Pull request by leocavalcante**
Despite it isn't popular as Slim, Silex and Lumen, it is getting closer to Bullet and Proton.
But the main reason IMHO to get Siler listed is about its uniqueness approach on how PHP micro frameworks, libraries and web applications are made.
It proposes plain old functions and files over classes in a nice structured, PSR compilant and well tested way.

### CODE REVIEW

**Comment by IvanDelsinne** [comment]
Did small participation to Siler.

It's a very lightweight library containing almost only a single router and a few utilities.

Its aim is to just give a basic routing system and base operations to give full control of its developer on how the request lifecycle will be handled.

**Comment by leocavalcante** [comment]
Heads up! [Siler](https://github.com/leocavalcante/siler) is stable now by [v1.0.0](https://packagist.org/packages/leocavalcante/siler). Almost 300 stars and 1k downloads.

**Comment by leocavalcante** [comment]
Siler just got listed as GraphQL server implementation: https://graphql.org/code/#siler-https-siler-leocavalcante-com-graphql-github-https-github-com-leocavalcante-siler

**Comment by leocavalcante** [comment]
Ping @ziadoz @josegonzalez

**Pull request closed without merging**
