### PR TITLE
Add Studio

### PR DESCRIPTION
**Pull request by ivan1986**
A workbench for developing Composer packages.

### CODE REVIEW

**Comment by josegonzalez** [comment]
How is this better/different from existing packages we list?

**Comment by ivan1986** [comment]
In list not exist packages with same functions
it's replace some repositories in dev enviroment - very usefull if write own composer package.

**Comment by josegonzalez** [comment]
This seems like the tooly package right under it, and some of it's functionality seems to be in composer already.

**Comment by ivan1986** [comment]
Ok, i just suggest

**Comment by josegonzalez** [comment]
Right. I'm asking you to justify your suggestion is all. Can you list a few ways this package is awesome?

**Pull request closed without merging**
