### PR TITLE
[static site generators] jigsaw

### PR DESCRIPTION
**Pull request by raphaelstolt**
Added Jigsaw to the static site generators section.

### CODE REVIEW

**Comment by josegonzalez** [comment]
I haven't merged this because I'm trying to think of a good metric for "awesome" repositories. Not to say your code isn't great, just don't want this list to become a "here is all the php code!" list. 

Will almost certainly involve removing some codebases where we have multiple implementations of the same thing.

**Comment by raphaelstolt** [comment]
It's not __my__ code, but IMHO it's defo a static site generator worthy to mention and list.

**Comment by jadb** [comment]
No tests 😞

**Comment by raphaelstolt** [comment]
Ok that's a valid metric point. :smile:

**Pull request closed without merging**
