### PR TITLE
Added Lumen to Micro Frameworks

### PR DESCRIPTION
**Pull request by efik**
Hello!:)
I think this should be here.

### CODE REVIEW

**Comment by italolelis** [comment]
:+1:

**Comment by harryhope** [comment]
+1

**Comment by mikethrussell** [comment]
+1

**Comment by aasanchez** [comment]
+1

**Comment by lucasfercunha** [comment]
+1

**Comment by aglipanci** [comment]
+1

**Comment by alioygur** [comment]
+1

**Comment by tleb** [comment]
Is anybody for this PR? :smile:

**Comment by efik** [comment]
Lol :smile: 
@ziadoz  forgot about this PR :)

**Comment by titolendable** [comment]
+1

**Comment by mygoare** [comment]
+1

**Comment by efik** [comment]
@ziadoz, do you want to merge this PR? :)

**Comment by Stichoza** [comment]
@efik, I think @ziadoz hates Lumen :smiley:  Make a fork named awesome-php-including-lumen :smile:

**Pull request closed without merging**
