### PR TITLE
Add IterTools PHP to Architectural section

### PR DESCRIPTION
**Pull request by Smoren**
Added [IterTools PHP](https://github.com/markrogoyski/itertools-php) - A library that provides functionality for working with iterable entities (similar to itertools library in Python).

### CODE REVIEW

**Comment by llaville** [comment]
Seems equivalent to https://github.com/nikic/iter !

**Comment by Smoren** [comment]
@llaville, thanks for feedback!

PHP iterTools is similar to [iter](https://github.com/nikic/iter) but not equivalent because it provides a lot more functionality. Please look at the documentation in the [README](https://github.com/markrogoyski/itertools-php) of the project.

**Comment by Smoren** [comment]
Functions provided by [iter](https://github.com/nikic/iter) (41):

* all
* any
* apply
* chain
* chunk
* chunkWithKeys
* count
* drop
* dropWhile
* enumerate
* filter
* flatMap
* flatten
* flip
* fromPairs
* isEmpty
* isIterable
* join
* keys
* map
* mapKeys
* mapWithKeys
* product
* range
* recurse
* reduce
* reductions
* reindex
* repeat
* search
* slice
* split
* take
* takeWhile
* toArray
* toArrayWithKeys
* toIter
* toPairs
* values
* zip
* zipKeyValue

Methods provided by [IterTools PHP](https://github.com/markrogoyski/itertools-php) (78 excluding steam functionality):

* allMatch
* anyMatch
* arePermutations
* arePermutationsCoercive
* asort
* chain
* choice
* chunkwise
* chunkwiseOverlap
* coinFlip
* compress
* compressAssociative
* count
* cycle
* distinct
* dropWhile
* exactlyN
* filter
* filterFalse
* filterKeys
* filterTrue
* flatMap
* flatten
* groupBy
* intersection
* intersectionCoercive
* isPartitioned
* isReversed
* isSorted
* limit
* map
* noneMatch
* number
* pairwise
* partialIntersection
* partialIntersectionCoercive
* percentage
* readCsv
* readLines
* reindex
* repeat
* repeat
* reverse
* rockPaperScissors
* runningAverage
* runningDifference
* runningMax
* runningMin
* runningProduct
* runningTotal
* same
* sameCount
* slice
* sort
* string
* symmetricDifference
* symmetricDifferenceCoercive
* takeWhile
* tee
* toArray
* toAssociativeArray
* toAverage
* toCount
* toFirst
* toFirstAndLast
* toIterator
* toLast
* toMax
* toMin
* toMinMax
* toProduct
* toRange
* toString
* toSum
* toValue
* zip
* zipEqual
* zipLongest

**Comment by Smoren** [comment]
* [iter](https://github.com/nikic/iter) provides 41 functions.
* [IterTools PHP](https://github.com/markrogoyski/itertools-php) provides 78 methods excluding stream functionality.

Here is a comparison:

|[IterTools PHP](https://github.com/markrogoyski/itertools-php)|[iter](https://github.com/nikic/iter)|
|---|---|
|[Multi::chain](https://github.com/markrogoyski/itertools-php#chain)|[chain](https://github.com/nikic/iter/blob/master/src/iter.php#L418)
|[Multi::zip](https://github.com/markrogoyski/itertools-php#zip)|[zip](https://github.com/nikic/iter/blob/master/src/iter.php#L360)
|[Multi::zipEqual](https://github.com/markrogoyski/itertools-php#zipEqual)|-|
|[Multi::zipLongest](https://github.com/markrogoyski/itertools-php#zipLongest)|-|
|-|[zipKeyValue](https://github.com/nikic/iter/blob/master/src/iter.php#L392)
|[Single::chunkwise](https://github.com/markrogoyski/itertools-php#chunkwise)|[chunk](https://github.com/nikic/iter/blob/master/src/iter.php#L837)
|[Single::chunkwiseOverlap](https://github.com/markrogoyski/itertools-php#chunkwise-Overlap)|-|
|-|[chunkWithKeys](https://github.com/nikic/iter/blob/master/src/iter.php#L894)
|[Single::compress](https://github.com/markrogoyski/itertools-php#compress)|-|
|[Single::compressAssociative](https://github.com/markrogoyski/itertools-php#compress-Associative)|-|
|-|[drop](https://github.com/nikic/iter/blob/master/src/iter.php#L562)
|[Single::dropWhile](https://github.com/markrogoyski/itertools-php#drop-While)|[dropWhile](https://github.com/nikic/iter/blob/master/src/iter.php#L741)
|-|[enumerate](https://github.com/nikic/iter/blob/master/src/iter.php#L240), [toPairs](https://github.com/nikic/iter/blob/master/src/iter.php#L251) (equivalents of each other, but not equivalents of [Single::pairwise](https://github.com/markrogoyski/itertools-php#pairwise))|
|[Single::filter](https://github.com/markrogoyski/itertools-php#filter)|[filter](https://github.com/nikic/iter/blob/master/src/iter.php#L213)
|[Single::filterTrue](https://github.com/markrogoyski/itertools-php#filter-True)|-|
|[Single::filterFalse](https://github.com/markrogoyski/itertools-php#filter-False)|-|
|[Single::filterKeys](https://github.com/markrogoyski/itertools-php#filter-Keys)|-|
|[Single::flatMap](https://github.com/markrogoyski/itertools-php#flat-Map)|[flatMap](https://github.com/nikic/iter/blob/master/src/iter.php#L137)
|[Single::flatten](https://github.com/markrogoyski/itertools-php#flatten)|[flatten](https://github.com/nikic/iter/blob/master/src/iter.php#L770)
|-|[flip](https://github.com/nikic/iter/blob/master/src/iter.php#L819)
|[Single::groupBy](https://github.com/markrogoyski/itertools-php#group-By)|-|
|-|[keys](https://github.com/nikic/iter/blob/master/src/iter.php#L595)
|[Single::limit](https://github.com/markrogoyski/itertools-php#limit)|-|
|[Single::map](https://github.com/markrogoyski/itertools-php#map)|[map](https://github.com/nikic/iter/blob/master/src/iter.php#L60)
|-|[mapKeys](https://github.com/nikic/iter/blob/master/src/iter.php#L85)
|-|[mapWithKeys](https://github.com/nikic/iter/blob/master/src/iter.php#L108)
|[Single::pairwise](https://github.com/markrogoyski/itertools-php#pairwise)|-|
|-|[product](https://github.com/nikic/iter/blob/master/src/iter.php#L439)
|[Single::reindex](https://github.com/markrogoyski/itertools-php#reindex)|[reindex](https://github.com/nikic/iter/blob/master/src/iter.php#L161)
|[Single::repeat](https://github.com/markrogoyski/itertools-php#repeat)|[repeat](https://github.com/nikic/iter/blob/master/src/iter.php#L566)
|[Single::reverse](https://github.com/markrogoyski/itertools-php#reverse)|-|
|-|[recurse](https://github.com/nikic/iter/blob/master/src/iter.php#L1018)
|[Single::slice](https://github.com/markrogoyski/itertools-php#slice)|[slice](https://github.com/nikic/iter/blob/master/src/iter.php#L492)
|[Single::string](https://github.com/markrogoyski/itertools-php#string)|[split](https://github.com/nikic/iter/blob/master/src/iter.php#L925)
|-|[take](https://github.com/nikic/iter/blob/master/src/iter.php#L532)
|[Single::takeWhile](https://github.com/markrogoyski/itertools-php#take-While)|[takeWhile](https://github.com/nikic/iter/blob/master/src/iter.php#L716)
|[Infinite::count](https://github.com/markrogoyski/itertools-php#count)|[range](https://github.com/nikic/iter/blob/master/src/iter.php#L5)
|[Infinite::cycle](https://github.com/markrogoyski/itertools-php#cycle)|-|
|[Infinite::repeat](https://github.com/markrogoyski/itertools-php#repeat)|-|
|[Random::choice](https://github.com/markrogoyski/itertools-php#choice)|-|
|[Random::coinFlip](https://github.com/markrogoyski/itertools-php#coinFlip)|-|
|[Random::number](https://github.com/markrogoyski/itertools-php#number)|-|
|[Random::percentage](https://github.com/markrogoyski/itertools-php#percentage)|-|
|[Random::rockPaperScissors](https://github.com/markrogoyski/itertools-php#rockPaperScissors)|-|
|[Math::runningAverage](https://github.com/markrogoyski/itertools-php#running-Average)|-|
|[Math::runningDifference](https://github.com/markrogoyski/itertools-php#running-Difference)|-|
|[Math::runningMax](https://github.com/markrogoyski/itertools-php#running-Max)|-|
|[Math::runningMin](https://github.com/markrogoyski/itertools-php#running-Min)|-|
|[Math::runningProduct](https://github.com/markrogoyski/itertools-php#running-Product)|-|
|[Math::runningTotal](https://github.com/markrogoyski/itertools-php#running-Total)|-|
|[Set::distinct](https://github.com/markrogoyski/itertools-php#distinct)|-|
|[Set::intersection](https://github.com/markrogoyski/itertools-php#intersection)|-|
|[Set::intersectionCoercive](https://github.com/markrogoyski/itertools-php#intersection-Coercive)|-|
|[Set::partialIntersection](https://github.com/markrogoyski/itertools-php#partial-Intersection)|-|
|[Set::partialIntersectionCoercive](https://github.com/markrogoyski/itertools-php#partial-Intersection-Coercive)|-|
|[Set::symmetricDifference](https://github.com/markrogoyski/itertools-php#symmetric-Difference)|-|
|[Set::symmetricDifferenceCoercive](https://github.com/markrogoyski/itertools-php#symmetric-Difference-Coercive)|-|
|[Sort::asort](https://github.com/markrogoyski/itertools-php#asort)|-|
|[Sort::sort](https://github.com/markrogoyski/itertools-php#sort)|-|
|[File::readCsv](https://github.com/markrogoyski/itertools-php#read-Csv)|-|
|[File::readLines](https://github.com/markrogoyski/itertools-php#read-Lines)|-|
|-|[fromPairs](https://github.com/nikic/iter/blob/master/src/iter.php#L274)
|[Transform::tee](https://github.com/markrogoyski/itertools-php#tee)|-|
|[Transform::toArray](https://github.com/markrogoyski/itertools-php#to-Array)|[toArray](https://github.com/nikic/iter/blob/master/src/iter.php#L1072)
|[Transform::toAssociativeArray](https://github.com/markrogoyski/itertools-php#to-Associative-Array)|[toArrayWithKeys](https://github.com/nikic/iter/blob/master/src/iter.php#L1098)
|[Transform::toIterator](https://github.com/markrogoyski/itertools-php#to-Iterator)|[toIter](https://github.com/nikic/iter/blob/master/src/iter.php#L1041)
|[Summary::allMatch](https://github.com/markrogoyski/itertools-php#all-Match)|[all](https://github.com/nikic/iter/blob/master/src/iter.php#L660)
|[Summary::anyMatch](https://github.com/markrogoyski/itertools-php#any-Match)|[any](https://github.com/nikic/iter/blob/master/src/iter.php#L631)
|[Summary::arePermutations](https://github.com/markrogoyski/itertools-php#are-Permutations)|-|
|[Summary::arePermutationsCoercive](https://github.com/markrogoyski/itertools-php#are-Permutations-Coercive)|-|
|[Summary::exactlyN](https://github.com/markrogoyski/itertools-php#exactly-N)|-|
|-|[isEmpty](https://github.com/nikic/iter/blob/master/src/iter.php#L993)
|-|[isIterable](https://github.com/nikic/iter/blob/master/src/iter.php#L1125)
|[Stream::callForEach](https://github.com/markrogoyski/itertools-php#call-For-Each)|[apply](https://github.com/nikic/iter/blob/master/src/iter.php#L192)
|[Summary::isPartitioned](https://github.com/markrogoyski/itertools-php#is-Partitioned)|-|
|[Summary::isSorted](https://github.com/markrogoyski/itertools-php#is-Sorted)|-|
|[Summary::isReversed](https://github.com/markrogoyski/itertools-php#is-Reversed)|-|
|[Summary::noneMatch](https://github.com/markrogoyski/itertools-php#none-Match)|-|
|[Summary::same](https://github.com/markrogoyski/itertools-php#same)|-|
|[Summary::sameCount](https://github.com/markrogoyski/itertools-php#same-Count)|-|
|-|[reductions](https://github.com/nikic/iter/blob/master/src/iter.php#L328)
|-|[search](https://github.com/nikic/iter/blob/master/src/iter.php#L688)
|[Reduce::toAverage](https://github.com/markrogoyski/itertools-php#to-Average)|-|
|[Reduce::toCount](https://github.com/markrogoyski/itertools-php#to-Count)|[count](https://github.com/nikic/iter/blob/master/src/iter.php#L957)
|[Reduce::toFirst](https://github.com/markrogoyski/itertools-php#to-First)|-|
|[Reduce::toFirstAndLast](https://github.com/markrogoyski/itertools-php#to-First-And-Last)|-|
|[Reduce::toLast](https://github.com/markrogoyski/itertools-php#to-Last)|-|
|[Reduce::toMax](https://github.com/markrogoyski/itertools-php#to-Max)|-|
|[Reduce::toMin](https://github.com/markrogoyski/itertools-php#to-Min)|-|
|[Reduce::toMinMax](https://github.com/markrogoyski/itertools-php#to-Min-Max)|-|
|[Reduce::toProduct](https://github.com/markrogoyski/itertools-php#to-Product)|-|
|[Reduce::toRange](https://github.com/markrogoyski/itertools-php#to-Range)|-|
|[Reduce::toString](https://github.com/markrogoyski/itertools-php#to-String)|[join](https://github.com/nikic/iter/blob/master/src/iter.php#L898)
|[Reduce::toSum](https://github.com/markrogoyski/itertools-php#to-Sum)|-|
|[Reduce::toValue](https://github.com/markrogoyski/itertools-php#to-Value)|[reduce](https://github.com/nikic/iter/blob/master/src/iter.php#L298)
|-|[values](https://github.com/nikic/iter/blob/master/src/iter.php#L613)

**Comment by llaville** [comment]
@Smoren thanks for compare report

**Comment by Smoren** [comment]
BTW, IterTools PHP is mentioned in [PHP Annotated february 2023](https://blog.jetbrains.com/phpstorm/2023/02/php-annotated-february-2023/) by JetBrains.

**Comment by Smoren** [comment]
@ziadoz thank you for merging this PR!

**Pull request merged**
