### PR TITLE
add ddev, and docksal to development environment

### PR DESCRIPTION
**Pull request by souhaiebtar**
add ddev and devilbox to development environment

### CODE REVIEW

**Comment by souhaiebtar** [comment]
@dereuromark  i did remove Devilbox as requested

**Comment by souhaiebtar** [comment]
@alexkart i did updated to respect the contribution Guidelines

**Comment by dereuromark** [comment]
Squash merge should be fine :+1:

**Comment by alexkart** [comment]
Moved Docksal entry one position down

**Review by alexkart — APPROVED** [review]

**Pull request merged**
