### PR TITLE
Added PHP Censor

### PR DESCRIPTION
**Pull request by corpsee**
Added PHP Censor - An open source self-hosted continuous integration server for PHP projects (Fork of PHPCI)

### CODE REVIEW

**Comment by josegonzalez** [comment]
Any reason why this is a fork and not a contribution back to the main project?

**Comment by pothi** [comment]
@josegonzalez Direct quote from https://github.com/ziadoz/awesome-php/blob/master/CONTRIBUTING.md ...

> Unfortunately, not every library, tool or framework can be considered for inclusion. The aim of Awesome PHP is to be a concise list of noteworthy and interesting software written in modern PHP. Therefore, suggested software should:
> 
> a) Be widely recommended regardless of personal opinion b) Well known or discussed within the PHP community c) Be unique in its approach or function d) Fill a niche gap in the market

**Comment by josegonzalez** [comment]
@pothi thanks for quoting the contributing docs at me.

@corpsee Any reason why your fork should be included over the existing PHPCI entry?

**Comment by corpsee** [comment]
@josegonzalez PHPCI in fact abandoned, pull requests waits for years. PHP Censor fixed a lot of PHPCI bugs, It has LDAP authentication and PostgreSQL support unlike PHPCI etc.

**Comment by josegonzalez** [comment]
The last commit was actually a month ago. If anything, I'd rather we have one or the other.

**Pull request closed without merging**
