### PR TITLE
add ThinkPHP

### PR DESCRIPTION
**Pull request by yunheli**

### CODE REVIEW

**Comment by tleb** [comment]
* Links to 404.
* Description should probably be in english.

**Comment by yunheli** [comment]
@tleb  I am so sorry

**Comment by tleb** [comment]
The sad thing is that this lib has no english documentation, so those who find it in this list will not be able to use it.

**Comment by yunheli** [comment]
I see, thank you @tleb

**Comment by tleb** [comment]
I am no maintainer, so I have no word on what happens with this, just my opinion.

Is there no list in chinese you could add this to?

**Comment by Jaggle** [comment]
@tleb most Chinese use thinkPHP, but it is really not good designed

**Pull request closed without merging**
