### PR TITLE
[queue] tarantool-php/queue

### PR DESCRIPTION
**Pull request by rybakit**
https://github.com/tarantool-php/queue

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you rebase this onto master?

**Comment by rybakit** [comment]
@josegonzalez Done.

**Comment by josegonzalez** [comment]
Shit, can you also put it in the right alphabetical order? Sorry for not mentioning that :(

**Comment by rybakit** [comment]
Fixed.

**Comment by josegonzalez** [comment]
My cat approves.

**Comment by rybakit** [comment]
Thanks! ;)

**Pull request merged**
