### PR TITLE
Elasticsearch library added.

### PR DESCRIPTION
**Pull request by vrkansagara**
Elasticsearch library added.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Please insert this in alphabetical order.

**Comment by ReadmeCritic** [comment]
@josegonzalez `elasticsearch-php` is already on the list under **Search**

**Comment by josegonzalez** [comment]
Lovely! Closing.

**Comment by vrkansagara** [comment]
If  you dont mind @ReadmeCritic  than I would like to see the nosql database under the same what I have made a PR for it.

Ping:- @josegonzalez

**Comment by ReadmeCritic** [comment]
I don't mind
Should the lib be moved or duplicated?

**Pull request closed without merging**
