### PR TITLE
CodeIgniter framework added to the list

### PR DESCRIPTION
**Pull request by mrNo0b**
CodeIgniter must be listed here.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why must it be listed here?

**Comment by josegonzalez** [comment]
(I realize thats a pedantic remark, we just have to hold every entry to the same standards).

**Comment by dereuromark** [comment]
Dup of https://github.com/ziadoz/awesome-php/pull/693 it seems

**Comment by ziadoz** [comment]
Thanks for the suggestion.

**Pull request closed without merging**
