### PR TITLE
Add Brick\Math

### PR DESCRIPTION
**Pull request by BenMorel**
[Brick\Math](https://github.com/brick/math) offers an implementation of large numbers:

- `BigInteger`
- `BigDecimal`
- `BigRational`

It works with either GMP or BCMath, and can even work without these extensions thanks to a pure PHP calculator. The library automatically uses the fastest calculator implementation available.

### CODE REVIEW

**Comment by BenMorel** [comment]
Any update on this one? `Brick\Math` is a quite mature project now:

- 4 years old
- 30 releases (current version: 0.8.2)
- 500,000+ downloads

It would be cool to help it gain further traction :+1:

**Comment by BenMorel** [comment]
[One million downloads](https://packagist.org/packages/brick/math/stats) today 🎉

Still no willingness to add it to this list?

**Comment by BenMorel** [comment]
[2 million downloads](https://packagist.org/packages/brick/math/stats) today 🎉

**Comment by jadb** [comment]
Sorry, just got lost in all the PRs. Thanks 👍

**Comment by BenMorel** [comment]
Thanks to you!

**Pull request merged**
