### PR TITLE
[Data Structure and Storage] Added Knapsack

### PR DESCRIPTION
**Pull request by DusanKasan**
Added Knapsack, a collection library inspired by Clojure's sequences. Its collections are immutable and lazy where possible. All operations are available as pure functions and as collection pipeline object's methods. It has no dependencies.

### CODE REVIEW

**Comment by josegonzalez** [comment]
How is this any better or different from the existing collections libraries already listed?

**Comment by DusanKasan** [comment]
Hi, 

by providing uniform interface/handling for all data sets the only direct contender on this list is the https://github.com/cakephp/collection - the others are more about optimizing performance. While Cake's collection class provides most of the functionality proposed by Knapsack, Knapsack goes further and has methods like interleave, takeWhile, etc. and provides all of its functionality as functions too. 

Also, i don't see Cake's tests anywhere in the repo and Knapsack is 99% covered, has automated CI tests in place and follows semver.

Hope you will consider adding Knapsack to this list :)

**Comment by josegonzalez** [comment]
Note: Cakes collection library is a submodule split, and tests are in the CakePHP/CakePHP repo for it.

I'll take a further like into your library now :)

**Comment by jadb** [comment]
I will let @josegonzalez make the call since he was handling it. But code/docs look good, nice job!

**Comment by DusanKasan** [comment]
@josegonzalez or @jadb, could you have a look and merge/reject please?

**Pull request merged**
