### PR TITLE
[Filtering and Validation] Add Wixel/GUMP

### PR DESCRIPTION
**Pull request by filisko**

### CODE REVIEW

**Comment by filisko** [comment]
@jadb hi?

**Comment by josegonzalez** [comment]
How is this different/better than existing solutions we list?

**Comment by filisko** [comment]
How different are the existing solutions from each other?

**Comment by josegonzalez** [comment]
I don't know, but its on you to prove that your submission belongs on this list.

**Comment by filisko** [comment]
I'm not the owner of this library, just a collaborator and I think that people may be interested in this library as is very easy to set rules and validate.

**Comment by josegonzalez** [comment]
Right, but how is it different/better than the solutions we've listed? I'm sure the other libraries also are easy to use for adding rules and validation, otherwise they wouldn't be here.

**Comment by filisko** [comment]
It has filtering integrated as well, so you can filter and validate.

**Pull request closed without merging**
