### PR TITLE
Adding Laravel-Zero

### PR DESCRIPTION
**Pull request by danielsuguimoto**
Adding laravel-zero, a micro-framework for console application written in Laravel.

Github: 
- https://github.com/laravel-zero/laravel-zero
- https://github.com/laravel-zero/framework

Docs: https://laravel-zero.com/docs/introduction/

Packagist: https://packagist.org/packages/laravel-zero/laravel-zero

### CODE REVIEW

**Comment by jadb** [comment]
Can you please re-order alphabetically? Ignore the Expressive library which I'll re-order in a separate PR.

**Comment by danielsuguimoto** [comment]
@jadb Ok, thanks! Done!

**Comment by jadb** [comment]
Thanks! 👍

**Comment by danielsuguimoto** [comment]
@jadb You're welcome!

**Pull request merged**
