### PR TITLE
Add composer-unused

### PR DESCRIPTION
**Pull request by icanhazstring**
Add composer-unused in `Dependency Manager Extras`-Section.
This is a small CLI Tool which scans you `composer.json` of any unused package by doing a static analysis of used symbols in your code.

URL: https://github.com/composer-unused/composer-unused

### CODE REVIEW

**Comment by jadb** [comment]
Can you please include in the other PR or wait for it to be merged to also re-order this one alphabetically?

**Comment by icanhazstring** [comment]
OK. Will include it in the other one and close this. Thanks 👍

**Comment by icanhazstring** [comment]
@jadb better late than never I guess ;)
Merged #1085 into this one.

**Comment by ziadoz** [comment]
Thanks!

**Pull request merged**
