### PR TITLE
Updates to Aura & Radar; adds PDS.

### PR DESCRIPTION
**Pull request by pmjones**
Changes are:

- Added topic-specific Aura libraries.
- Linked Aura Framework directly.
- Added Aura as a component library.
- Added PHP-PDS website.
- Moved Radar to micro-frameworks.
- "Typo" fix on MLAPHP ("moderni(s|z)ation")

Please let me know if these are appropriate or not, and thanks for putting together this list in the first place.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Do we really need to call out aura under each of the sections? I think one at the framework level is good enough.

**Comment by pmjones** [comment]
@josegonzalez Maybe, maybe not. Aura's a funny bird, in that it is first-and-foremost a library collection; the framework is composed secondarily of those libraries. (As precedent, you might find that Cake shows up a few times.)

**Comment by josegonzalez** [comment]
Interesting. I'd say that unless your solution is drastically better/different than existing ones, you shouldn't re-add it. Intl is a good example of that (both aura and cake are included) where there aren't many solutions and the two there are different enough from each other that they both warrant inclusion.

**Comment by pmjones** [comment]
> I'd say that unless your solution is drastically better/different than existing ones

Of course, I think they are, but then I would; I invite you to review them yourself and judge accordingly.

**Comment by josegonzalez** [comment]
Ugh more work. I'll try and get to this tonight (and a few other prs...)

**Comment by pmjones** [comment]
Sure; I'm in no hurry. (I'll also add that the Aura libraries in some cases predate the other libraries, which may or may not factor into whether they should be included or not; e.g. Aura.View vs Foil, Plates, etc.)

**Comment by pmjones** [comment]
@josegonzalez et al -- any further thoughts on this?

**Comment by josegonzalez** [comment]
Fuck it.

**Pull request merged**
