### PR TITLE
[date and time] fightbulc/moment.php

### PR DESCRIPTION
**Pull request by fightbulc**
https://github.com/fightbulc/moment.php

### CODE REVIEW

**Comment by ecolinet** [comment]
Looks very useful !

+1

**Comment by josegonzalez** [comment]
Can you rebase this onto master? I will merge it once you do. Feel free to close if not.

**Comment by fightbulc** [comment]
@josegonzalez all done.

**Comment by kamilsk** [comment]
@fightbulc, now your pr contains 250+ commits... How did you make rebase?

**Comment by fightbulc** [comment]
@kamilsk I'll go ahead and create a new PR to solve this mess.

**Comment by fightbulc** [comment]
@kamilsk new PR: https://github.com/ziadoz/awesome-php/pull/620

**Comment by kamilsk** [comment]
@fightbulc, thank you!

**Pull request closed without merging**
