### PR TITLE
Add Fakerino a modern fake data generator framework

### PR DESCRIPTION
**Pull request by niklongstone**

### CODE REVIEW

**Comment by tleb** [comment]
I am not certain about the integration of this repo in this list:

* really recent (first commit 22/02/15);
* only one contributor;
* why is this installation through a `composer create-project` and not a simple `require` ? I don't think a fake data generator should be the base of an app.

I haven't tested the library, but I think that more active users is needed for a lib to go in this list.

**Comment by niklongstone** [comment]
so, please update the CONTRIBUTING.md inserting minimum requirements for this list.

**Comment by tleb** [comment]
I do not manage this list, I just give my opinion. @ziadoz might have a completely different opinion.

**Comment by niklongstone** [comment]
I understand now why Justin Bieber is so popular....

**Comment by tleb** [comment]
Euh, what?

* PHP
* Github
* list
* awesome
* contributing
* Justing Bieber

Find the link. You have two hours.

**Comment by beautyface** [comment]
I'm to pretty to read this.

**Pull request closed without merging**
