### PR TITLE
Added Processwire, Microweber, Cockpit, Sphido, Latte.

### PR DESCRIPTION
**Pull request by clsource**
http://processwire.com/
https://microweber.com/
http://getcockpit.com/
http://www.sphido.org/
https://latte.nette.org

### CODE REVIEW

**Comment by peter-mw** [comment]
+1

**Comment by ash-rain** [comment]
+1

**Comment by bocharsky-bw** [comment]
I think better to use separate PRs for each framework/cms/library . It'll be easy to merge them.

**Comment by josegonzalez** [comment]
Please split this out into separate PRs.

**Pull request closed without merging**
