### PR TITLE
add php extension swoole

### PR DESCRIPTION
**Pull request by toxmc**
Swoole is an event-driven asynchronous & concurrent networking communication framework with high performance written only in C for PHP.

### CODE REVIEW

**Comment by smalleyes** [comment]
Why Swoole?

Traditional PHP applications almost always run behind Apache/Nginx, without much control of the request. This brings several limitations:

All memory will be freed after request. All PHP code needs be re-compiled on every request. Even with opcache enabled, all opcode still needs to be re-executed.
It is almost impossible to implement long connections and connections pooling techniques.
Implementing asynchronous tasks requires 3rd party queue servers, such as rabbitmq and beanstalkd.
Implementing realtime applications such as chatting server requires 3rd party languages, nodejs for example.
This why Swoole appeared. Swoole extends the use cases of PHP, and brings all these possibilities to the PHP world. By using Swoole, you can build enhanced web applications with more control, real-time chatting servers, etc more easily.

**Comment by Gemorroj** [comment]
So, Swoole looks good. But he has a bad/outdated documentation.

**Comment by smalleyes** [comment]
Swoole documents will get better

**Comment by smalleyes** [comment]
lol.  this suggest can be merged？ why not.

**Pull request merged**
