### PR TITLE
[miscellaneous] ARCANEDEV/SEO-Helper

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
[SEO-Helper](https://github.com/ARCANEDEV/SEO-Helper) - Provides tools and helpers for SEO (Search Engine Optimization).

See #490

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Hi @jadb, i just want to know if you can take a look again for this PR. It just reached 100 stars 🎉 

Any response will be greatly appreciated 👍

**Comment by arcanedev-maroc** [comment]
Hi, this is a friendly reminder to know if there is any decision about this PR.

Best regards.

cc: @jadb @josegonzalez

**Comment by arcanedev-maroc** [comment]
**Update:** Solved the conflicts

**Comment by ziadoz** [comment]
Thanks for the suggestion.

**Pull request closed without merging**
