### PR TITLE
Fixed typo on 'Lambda'.

### PR DESCRIPTION
**Pull request by saulotoledo**
Fixed typo on 'Lambda'.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you split off the suggestions?

**Comment by saulotoledo** [comment]
Hi josegonzalez. I thought I should just separate commits, and not the pull requests. My mistake. I will do it now.

**Comment by saulotoledo** [comment]
@josegonzalez, all commits are ready. Let me know if there is something more I can do.

**Comment by jadb** [comment]
Thanks!

**Pull request merged**
