### PR TITLE
[testing] Fakerino/Fakerino

### PR DESCRIPTION
**Pull request by niklongstone**
From the repo readme:
- Fake **complex data** (e.g. person: name, surname, hobby, country, ... ).
- Fake **single data** (e.g. name, surname, integer, text, ...).
- Fake data in **different languages**.
- Fake **regular expression** data (e.g. url => '`/www\.\w+\.com/`').
- Fake data multiple times.
- Fake a **database** table row/s with one line of code.
- Fake a **Twig** string or file automatically (e.g. Hello Mr {{ surname }})
- Fake a PHP **object/entity** in one line of code (fills public properties and setters with fake data).
- Support **JSON**, **array** and string output.
- Support array, **Yaml**, **XML**, **PHP**, **Txt** and **Ini** configurations.
- Fake from **command line** interface.
- Fake 500,000 data in 1 minute.

### CODE REVIEW

**Comment by josegonzalez** [comment]
While I applaud the work, I don't see how this is any better than the existing packages. Do you mind explaining why?

**Comment by niklongstone** [comment]
@josegonzalez thanks for the time you spent to evaluate the package.

Fakerino mailnly follows some big rules: good structure, complete, easy-to-use, easy to implement, I can go further asserting that Fakerino has:
1. A clean separation between fake data and code functionalities, for example you can plug your own data(use the samples provided) or extend a cutstom class to create different output without waiting for a new code release.
2. An all-in-one library, all the main fake features are there, it's up to the user to use them or not, that's why it's more a framework than a single tool.
3. A fast and easy to use personality.

Below a list of its key features, most of them not provided by any existing PHP package:
* It has a built-in in command line tool.
* You can seed a database table and optionally let Fakerino to guess the column data (i.e. seed thousands of rows in one line). `$fakerino->num(100)->fakeTable('tableName');`
* Supports regular expressions (PCRE). You can describe fake data with a regular expression.
* There is a Symfony integration that includes a Twig extension as well, so you can fake data also directly inside a view, quite useful to mock third party API. There are a Laravel and a Nette integrations too.
* It's easy to fake an entire document like an HTML page or a JSON response providing a Twig template to fake `$fakerino->fakeTemplate('Hello Mr {{ surname }}');` or `$fakerino->fakeTemplate('template/path/response.xml');` (again just one line).
* You can use a configuration file (ini, yaml, xml or php) to fake group of data, or describe new data, for example if You can describe a Dad and a Mom fake data (name, surname, ...) and you can fake a 'family' `$fakerino->fake('family');`, or you can define a new kind of data without PHP code changes.
* Can fill an entity class with fake data, guessing the value.
* Easy to extend or implement, good test coverage and documentation [fakerino.io](fakerino.io) as a modern tool must be.

Finally, just to recap, the Fakerino qualities are inside its modern code structure, new features and simplicity. 

Thanks

**Comment by niklongstone** [comment]
Any news about this one?

**Comment by ziadoz** [comment]
Thanks for the suggestion.

**Pull request closed without merging**
