### PR TITLE
add prooph components for event sourcing and message bus

### PR DESCRIPTION
**Pull request by sandrokeil**

### CODE REVIEW

**Comment by sandrokeil** [comment]
@ziadoz Any news for this?

**Comment by jadb** [comment]
@sandrokeil, looks interesting. Can you rebase?

**Comment by josegonzalez** [comment]
Needs rebase.

**Comment by sandrokeil** [comment]
Done

**Comment by sandrokeil** [comment]
Seems some other URIs are not available.

```
Checking white listed URLs: ???✓??
> White listed:
  1. 500 http://blog.astrumfutura.com/2013/03/predicting-random-numbers-in-php-its-easier-than-you-think/
  2. 500 http://blog.astrumfutura.com/2013/04/20-point-list-for-preventing-cross-site-scripting-in-php/
  3. 500 http://blog.astrumfutura.com/2012/04/php-innocent-villagefolk-or-a-pillagin-pirate/
  4. 200 http://auraphp.com/
  5. https://igor.io/2013/01/07/composer-versioning.html SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure
  6. https://igor.io/2013/02/07/composer-stability-flags.html SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure
Issues :-(
> Links 
  1. 503 https://www.random.org/
  2. 301 http://seancoates.com/blogs/use-env → http://seancoates.com/blogs/use-env/
> Dupes 
  None ✓
```

**Comment by josegonzalez** [comment]
Fixed the seancotes link, mind rebasing again?

**Pull request merged**
