### PR TITLE
Add CodeIgniter PHP Framework

### PR DESCRIPTION
**Pull request by SunDi3yansyah**

### CODE REVIEW

**Comment by tleb** [comment]
[Please](https://github.com/ziadoz/awesome-php/issues?q=codeigniter).

**Comment by SunDi3yansyah** [comment]
LOL :grin: arrogant, don't merge :smiling_imp:

**Comment by tleb** [comment]
Did you actually come to give us your repo link?

**Comment by SunDi3yansyah** [comment]
What do you mean?

**Comment by SunDi3yansyah** [comment]
https://github.com/sindresorhus/awesome/pull/356

**Pull request closed without merging**
