### PR TITLE
added PHP infrastructure section and appserver.io

### PR DESCRIPTION
**Pull request by wick-ed**
Added appserver.io within a new category as others did not seem to fit.

Please have a look at:
- http://appserver.io
- https://github.com/appserver-io/appserver

### CODE REVIEW

**Comment by smolinari** [comment]
:+1: for adding appserver to the list!

Scott

**Comment by zelgerj** [comment]
:+1: go for it! ;)

**Comment by ziadoz** [comment]
Thanks, I've merged this.

**Comment by smolinari** [comment]
Thank you too. Great list of resources for PHP!

Scott

**Pull request merged**
