### PR TITLE
Remove True Random

### PR DESCRIPTION
**Pull request by kelunik**
I don't see why this should be awesome. PHP offers a CSPRNG and mt_rand and covers all use cases well.

### CODE REVIEW

**Comment by golaod** [comment]
Because both CSPRNG and mt_rand are **pseudo** random solutions, whereas random.org is free API which delivers truly random results.

**Comment by kelunik** [comment]
@golaod Computers can't generate truly random numbers, so what's the point? What's the use case? What's the advantage?

**Comment by juliangut** [comment]
Not a fan of making external requests for (pseudo-)random numbers @kelunik @josegonzalez but to honor randomness... 

from random.org (bold text is mine):

> RANDOM.ORG offers true random numbers to anyone on the Internet. The **randomness comes from atmospheric noise**, which for many purposes is better than the pseudo-random number algorithms typically used in computer programs.

**Comment by kelunik** [comment]
@juliangut @golaod Feel free to resubmit it to another category like https://github.com/ziadoz/awesome-php#third-party-apis, but it definitely doesn't fit into Security.

**Pull request merged**
