### PR TITLE
[authentication and authorization] atayahmet/glad

### PR DESCRIPTION
**Pull request by atayahmet**
[Documentation Status](https://readthedocs.org/projects/glad/?badge=latest) [Build Status](https://scrutinizer-ci.com/g/atayahmet/glad/build-status/master) [Scrutinizer Code Quality](https://scrutinizer-ci.com/g/atayahmet/glad/?branch=master)  [Total Downloads](https://packagist.org/packages/atayahmet/glad) [License](https://packagist.org/packages/atayahmet/glad) [Code Climate](https://codeclimate.com/github/atayahmet/glad)

An ideal package for fast and easy use.

add to composer.json require section:
```php
"atayahmet/glad": "1.0.*@dev"
```

after run the:
```php
$ composer update
```
[Click for Documentation](http://glad.readthedocs.org/en/latest/)

Gitter Chat:

[Gitter](https://gitter.im/atayahmet/glad?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

### CODE REVIEW

**Comment by tleb** [comment]
Not sure the description is great.

> An ideal package for fast and easy use.

**Comment by rkrx** [comment]
Don't know if your component is good. Can't read the docs. What is that?

**Comment by atayahmet** [comment]
Description may be inadequate, but I will edit.  This authentication package and is preparing yet English documents. Current documentation Turkish

**Comment by josegonzalez** [comment]
While this looks like a great project, for a library that authentication, I think it's a bit young to add to a list of awesome tools. Looking forward to seeing how it turns out!

**Pull request closed without merging**
