### PR TITLE
[build tools] jonathantorres/construct

### PR DESCRIPTION
**Pull request by raphaelstolt**
Added `construct` to the `build tools` section.

### CODE REVIEW

**Comment by raphaelstolt** [comment]
What about that one? `Merge` or `close` please.

**Comment by josegonzalez** [comment]
Closing. Composer actually has this functionality via `create-project`, which seems like the more flexible way of doing things.

**Comment by raphaelstolt** [comment]
That's like comparing 🍎's to 🍒, but ✌️ .

**Comment by josegonzalez** [comment]
Well I'm willing to discuss. How is this project better? It didn't seem like it was breaking new ground.

**Comment by josegonzalez** [comment]
Right. I think what I'm saying is that you can create a custom project repository and use that as a skeleton for whatever you desire. All major frameworks have such a project, and composer users are more than encouraged to create their own.

**Comment by raphaelstolt** [comment]
Sure you can use a skeleton, but does it follow established conventions and in how many spots do I have to adjust things (e.g. package name)? 

Which frameworks allow the creation of a framework agnostic skeleton project? Really not aware of one. 

And your last sentence indicates an intrinsically solution which once again might turn away from established conventions.

**Pull request merged**
