### PR TITLE
[cms] Adding CMS section #27

### PR DESCRIPTION
**Pull request by darol100**
Fixes #27

### CODE REVIEW

**Comment by tleb** [comment]
Shouldn't the section be added to the TOC too?

**Comment by 27cm** [comment]
Section "Content Management Systems (CMS)" should have the description and go after "Components". Also there is redundant line between sections.

**Comment by darol100** [comment]
I have added to the TOC too and added after the "Components" and I remove the redundant line.

**Comment by josegonzalez** [comment]
Never heard of BackdropCMS.

That said, if you rebase this, I will merge it. Seems like a reasonable thing to do.

**Comment by ziadoz** [comment]
Thanks. I sorted and merged a version of this.

**Pull request closed without merging**
