### PR TITLE
Add Respect Family

### PR DESCRIPTION
**Pull request by williamespindola**

### CODE REVIEW

**Comment by ziadoz** [comment]
Thanks. I'd love to add these, but not whilst they're in pre-alpha/dev state. Definitely re-open this once they're considered stable, though.

**Comment by batusa** [comment]
@ziadoz it's 1.0 now (:

**Comment by rogeriopradoj** [comment]
@ziadoz: https://github.com/Respect/Validation/tree/1.0.0

**Comment by batusa** [comment]
@rogeriopradoj I just saw that Respect Validation is already on the README.md, the only "problem" is a typo, but there's a PR for this https://github.com/ziadoz/awesome-php/pull/494

in this PR the only one allowed would be the Config component which is 2.0

**Pull request closed without merging**
