### PR TITLE
Add some framework and security tools

### PR DESCRIPTION
**Pull request by zephyru5**

### CODE REVIEW

**Comment by tleb** [comment]
You should have a look at [the contributing rules](https://github.com/ziadoz/awesome-php/blob/master/CONTRIBUTING.md).

A XSS filter writed by PHP -> A XSS filter written in PHP (write is irregular + in a language, not by)

Also, with the *phpfetcher* entry, you deleted a newline, before the *Middlewares* section.

Seems like nice libs though!

**Comment by nic-d** [comment]
@tleb Surely it should be 'An XSS filter written in PHP', just nitpicking.

**Comment by tleb** [comment]
@nic-d Wait, is *x* a vowel?

**Comment by zephyru5** [comment]
@tleb oh,sorry! it should be "An XSS filter written in PHP",and x is a vower when it is the first letter of  the sentense ,it's so funny,haha~

**Comment by tleb** [comment]
Sorry to doubt, but I haven't find a proof of this, could you back this up with a source?

**Comment by zephyru5** [comment]
@tleb [stackexchange](http://english.stackexchange.com/questions/8181/does-one-use-a-or-an-before-the-word-x-ray)

**Comment by tleb** [comment]
Thanks!

**Comment by josegonzalez** [comment]
Please resubmit this as separate PRs. Thanks!

**Pull request closed without merging**
