### PR TITLE
Added Jigsaw

### PR DESCRIPTION
**Pull request by ricardobarantini**
Added Jigsaw, a static site generator with laravel's blade.

More info in:
https://github.com/tightenco/jigsaw

### CODE REVIEW

**Comment by josegonzalez** [comment]
How is this better or worse than other existing solutions?

**Comment by ricardobarantini** [comment]
I like the simplicity and features the Blade offers. Besides being easy to learn and understand.

**Comment by jadb** [comment]
Fair enough.

However, every awesome package listed comes with a minimal test coverage. Couldn't find any tests.

**Comment by berteltorp** [comment]
Jigsaw have added/improved test coverage since you checked 😃

https://github.com/tightenco/jigsaw/tree/master/tests

And still qualifies as awesome IMHO

**Pull request closed without merging**
