### PR TITLE
Add leaf php to micro frameworks

### PR DESCRIPTION
**Pull request by lakuapik**
leaf

### CODE REVIEW

**Comment by rkrx** [comment]
Why would someone use leaf who could also use Laravel?

The excessive use of static calls is really scaring me right now.

**Comment by lakuapik** [comment]
@rkrx imo, its a user preference. maybe some people has a use for it, and some does not. it does not matter. what matter is this is one of php gems that i think awesome enough to be added on the list.

**Comment by ziadoz** [comment]
Thanks for the suggestion.

**Comment by justbyitself** [comment]
Why not leaf? It's an active projectc like Slim but lighter. Add it, please.

**Comment by alexkart** [comment]
> Why not leaf? It's an active project like Slim but lighter. Add it, please.

Please create a new PR if you think it is worth adding, as this source repo has already been deleted.

**Pull request closed without merging**
