### PR TITLE
Add OXID eShop

### PR DESCRIPTION
**Pull request by rezonanc**
An open source e-commerce software for agencies with deadlines.

### CODE REVIEW

**Comment by jadb** [comment]
Hmm, not really 'awesome' - wouldn't you agree?

**Comment by rezonanc** [comment]
Everything depends on a point of view. I don't know what kind of criteria is used to mark an item as 'awesome' but I guess I would have to let others to decide :)

Reasons why I placed this item from my point of view:
* Product is in active development for more than 10 years (community edition is younger)
* It is a full package solution, i.e. you're getting fully functional e-shop just by installing it
* Recently it is undergoing with major changes in their code base (composer integration, responsive theme, ...)
* It's not advertised as being high performant one, but actually it is quite competitive performance wise compared to other e-commerce based solutions among PHP world
* Has strong commercial support for the ones who want to get the most and best out of it

**Comment by jadb** [comment]
Well, thanks for clearing some stuff. 

In my initial, very quick (described why below) check, I missed some of what you said. But for what it's worth here's how it went:

- didn't see any composer file which led me to think that it isn't up to date with modern PHP standards.

- in some of the folders, I saw lowercased files mixed with camel-cased ones and that's where I stopped. 

- the community didn't seem to have adopted it (less than 100 stars).

So as I said, thanks for clearing some stuff up and kudos to the team behind it for such a constant support. 

However, I still, personally, don't think it is yet ready to be included (maybe after all the cleanup and updates they are going through).

/cc @ziadoz @josegonzalez

**Comment by m1** [comment]
@rezonanc @jadb I agree that 'awesome' is kind of opinionated, I suggest there should be some form of 'awesome' guidelines for submitting a package - e.g. follow PHP standards, should probably use packagist downloads as the metric of how widely a package is used rather than use github stars -- this is a much better way of doing it rather than just having a select few people have the monopoly of choosing what is 'awesome'.

**Comment by jadb** [comment]
@m1 it's always been opinionated, that's the goal of a curation. It's not a *contest* or *marketing* platform.

That being said, I didn't close this waiting for others' opinions.

**Comment by rezonanc** [comment]
Let's try to make the best of it :)

I do agree that in terms of perfection this e-commerce platform is not perfect, but on the other hand which is?
But on the other side I also would like that this curated awesome PHP list would only contain the very best there is.

I'm totally ok not to merge this platform to the list ATM. But I also hope that this conversation will be a motivator for the product owners (the e-commerce platform) to "step-up the game" and improve the project so that it would also look more attractive for the developers also. And just to give them a little bit of help could you express some ideas/thoughts on what should be done to make that project more attractive? I don't expect you to take a lot of hours into account and give it a deep analysis, just first short impressions/thoughts that would come to mind.

I do hope that the day will come and someone from development team will re-post their project here in hope to be added to the list and seeing it as a sign of respect from the PHP developers and community.

**Comment by m1** [comment]
@jadb You kind of twisted my words there and made a point about nothing.

To reiterate; what I was saying is that there should be a base guideline for what can be submitted, e.g. take a note from a older, more mature and more community driven awesome list: https://github.com/markets/awesome-ruby -- check the CONTRIBUTING.md, there should be a quality standard like that, e.g. stable, tests, documented etc.

**Comment by jadb** [comment]
@rezonanc I wished I could, am not here to judge any code or suggest improvements. Their community is their number 1 concern and I am not part of it, so I can't comment on what/how to improve.

Always open to add it later.

@m1, please read this repository's contributing guidelines. A lot is said in there, and this PR doesn't meet some of the main points.

**Comment by m1** [comment]
@jadb I don't think you read what I said

**Comment by ziadoz** [comment]
@m1 This list has been running for four years ([almost to the day actually](https://gist.github.com/ziadoz/1677679/revisions?page=14)), albeit originally as a GitHub gist, so I'd say it's reasonably mature. So many other lists have been derived from this one, and it's been really awesome to see all the neat things they've done too.

I've recently improved the guidelines to be much clearer, drawing some inspiration from Awesome Java's along the way. This list isn't going to be of any use to anyone if every project that ticks off a bunch of arbitrary checkboxes which are trivial gets added. The reality is not every suggestion will get accepted.

**Comment by m1** [comment]
@ziadoz I wasn't saying that this repo wasn't mature, was simply commenting on that the awesome-ruby repo seems to be a smoother operation and more structured guidelines.

**Pull request closed without merging**
